ARG SUPERSET_VERSION=5.0.0

FROM apache/superset:${SUPERSET_VERSION}
COPY docker/requirements.txt /tmp/requirements.txt

USER root

RUN set -eux; \
    apt-get update; \
    apt-get -y upgrade; \
    apt-get -y autoremove; \
    apt-get clean; \
    /app/docker/pip-install.sh  -r /tmp/requirements.txt; \
    rm -f /tmp/requirements.txt; \
    rm -rf /var/lib/apt/lists/*

USER superset
