ARG SUPERSET_VERSION=5.0.0

FROM apache/superset:${SUPERSET_VERSION}
COPY docker/requirements.txt .

USER root

RUN set -eux; \
    apt-get update; \
    apt-get -y upgrade; \
    apt-get -y autoremove; \
    pip install --no-cache-dir -r requirements.txt; \
    rm -rf /var/lib/apt/lists/* requirements.txt

USER superset

